routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});
//Route::middleware('guest')->group(function () {
    Route::get( '/', 'IndexController@index' )->name('main');

    Route::post('/ajax/search', 'Views\SearchController@get');
    Route::post('/ajax/search/get_categories', 'Views\SearchController@get_categories');
    Route::post('/ajax/search/more', 'Views\SearchController@more');
    Route::get('/search/{query}', 'Views\SearchController@all');
    Route::get( '/product/{url}', 'Views\ProductController@show' )->name( 'product' );
    Route::get('/cart', 'Views\OrderController@cart')->name('cart');
//    Route::post('/cart', 'Views\OrderController@addToCart')->name('addToCart');
    Route::post('/ajax/addtocart', 'Views\OrderController@addToCartAjax')->name('addToCartAjax');
    Route::post('/ajax/select_variant', 'Views\OrderController@selectVariantAjax');
    Route::post('/ajax/apply_coupone', 'Views\OrderController@applyСouponeAjax');
    Route::post('/ajax/recalculate_discount', 'Views\OrderController@recalculateDiscountAjax');
    Route::post('/order', 'Views\OrderController@create')->name('createOrder');
    Route::get('/order/check', 'Views\OrderController@check');
    Route::post('/order/pay', 'Views\OrderController@pay');
    Route::post('/order/success', 'Views\OrderController@store');
    Route::get('/order/{hash}', 'Views\OrderController@show');
    Route::get('/kontakty', 'Views\PagesController@contacts');
    Route::get('/feed/yandex.xml', 'Views\PagesController@yandex');
    Route::get('/feed/google.xml', 'Views\PagesController@google');
    Route::post('/ajax/products', 'Views\ProductController@showMore');
    Route::post('/ajax/filter', 'Views\ProductController@filter');
    Route::post('/ajax/click', 'Views\ProductController@click');
    Route::post('/ajax/callback', 'Views\OrderController@callback' );
    Route::post('/ajax/by_one_click', 'Views\OrderController@by_one_click' );
    Route::post('/ajax/add_review', 'Views\ProductController@add_review' );
    Route::post('/ajax/variant_features', 'Admin\VoyagerProductsController@variant_features' );
    Route::post('/ajax/product_features', 'Views\ProductController@product_features' );

    Route::get('/sitemap.xml', 'Views\SitemapController@index');
    Route::get('/sitemap_p0{page}.xml', 'Views\SitemapController@page');


    Route::get( '/{url}', 'Views\ProductController@index' )->name( 'category' );
    Route::get( '/{url}/page-{page}', 'Views\ProductController@index' )->name( 'category' );



//    Route::get( '/{url}', 'Views\PagesController@show' )->name( 'page' );
//});

app/Mark.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Mark extends Model
{
    //Get seo_text as array
    public function getSeoAttribute()
    {
        return explode('|', $this->seo_text);
    }
}

resources/views/feeds/all_products.blade.php
<yml_catalog date="{{$date}}">
    <shop>
        <name>TOLLY</name>
        <company>TOLLY</company>
        <url>https://tolly.ru/</url>

        <currencies>
            <currency id="RUR" rate="1"/>
        </currencies>

        <categories>
            @foreach($categories as $category)
            <category id="{{$category->id}}"@if($category->parent_id > 0) parentId="{{$category->parent_id}}"@endif>{{$category->name}}</category>
            @endforeach
        </categories>

        <offers>
            @foreach($variants as $variant)
            <offer id="{{$variant->id}}" available="@if($variant->stock > 1){{'true'}}@else{{'false'}}@endif">
                <url>https://tolly.ru/product/{{$variant->id}}</url>
                <price>{{$variant->price}}</price>
                <currencyId>RUR</currencyId>
                <categoryId>{{$variant->product->categories[0]->id}}</categoryId>
                <picture>{{$variant->product->image}}</picture>
                <store>@if($variant->stock > 1){{'true'}}@else{{'false'}}@endif</store>
                <pickup>true</pickup>
                <delivery>true</delivery>
                <vendor>{{$variant->product->brand->name}}</vendor>
                <name>{{$variant->product->name}}@if($variant->product->seo) {{$variant->name}}, {{$variant->product->seo}}@else {{$variant->name}}@endif</name>
                <description>{{$variant->description}}</description>

                @foreach($variant->options as $option)
                <param name="{{$option['name']}}">{{$option['value']}}</param>
                @endforeach
            </offer>
            @endforeach
        </offers>
    </shop>
</yml_catalog>

resources/views/feeds/all_products_google.blade.php
<rss xmlns:g="http://base.google.com/ns/1.0" version="2.0">
    <channel>
        <title>TOLLY.RU</title>
        <link>https://tolly.ru/</link>
        <description>TOLLY.RU</description>
         @foreach($variants as $variant)
        <item>
            <g:id>{{$variant->id}}</g:id>
            <g:condition>new</g:condition>
            <g:title>{{$variant->product->name}} {{$variant->name}}</g:title>
            <g:description>{{$variant->description}}</g:description>
            <g:link>https://tolly.ru/product/{{$variant->id}}</g:link>
            <g:image_link>{{$variant->product->image}}</g:image_link>
            <g:availability>@if($variant->stock > 1){{'in stock'}}@else{{'out of stock'}}@endif</g:availability>
            <g:price>{{$variant->price}} RUB</g:price>
            <g:brand>{{$variant->product->brand->name}}</g:brand>
            <g:mpn>{{$variant->external_id}}</g:mpn>
            <g:google_product_category>{{$variant->product->categories[0]->name}}</g:google_product_category>
        </item>
         @endforeach
    </channel>
</rss>

resources/views/feeds/sitemap.blade.php
@php echo '<?xml version="1.0" encoding="UTF-8"?>';  @endphp
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>
        <loc>{{ url('sitemap_p00.xml') }}</loc>
        <lastmod>{{ date('Y-m-d') }}</lastmod>
    </sitemap>
    @if ($pages > 0)
        @for ($p = 1; $p <= $pages ; $p++)
            <sitemap>
                <loc>{{ url('sitemap_p0'.$p.'.xml') }}</loc>
                <lastmod>{{ date('Y-m-d') }}</lastmod>
            </sitemap>
        @endfor
    @endif
</sitemapindex>

resources/views/feeds/sitemap_categories.blade.php
@php echo '<?xml version="1.0" encoding="UTF-8"?>';  @endphp
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    @foreach ($items as $item)
        @if(($item->type == 'mc' && $bot) || $item->type == 'c')
            <url>
                <loc>{{ url($item->slug) }}</loc>
                <lastmod>{{ date('Y-m-d') }}</lastmod>
                <changefreq>daily</changefreq>
                <priority>0.8</priority>
            </url>
        @endif
    @endforeach
</urlset>

resources/views/feeds/sitemap_part.blade.php
@php echo '<?xml version="1.0" encoding="UTF-8"?>';  @endphp
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    @foreach ($items as $item)
        <url>
            <loc>{{ url('product', $item->id) }}</loc>
            <lastmod>{{ date('Y-m-d', strtotime($item->updated_at)) }}</lastmod>
            <changefreq>weekly</changefreq>
            <priority>0.7</priority>
        </url>
    @endforeach
</urlset>